name: Release & JitPack Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build release AAR
        run: ./gradlew :securitymodule:assembleRelease --stacktrace
      - name: Publish to local maven (for JitPack)
        run: ./gradlew :securitymodule:publish --stacktrace

